# URLS
BASE_URL = "http://localhost:8080/api"
SIGNUP_URL = "/user/signup"
SIGNIN_URL = "/user/signin"
ME_URL = "/user/me"
GAME_URL = "/game/"
GAME_START_URL = "/start"
GAME_STATUS_URL = "/status"
GAME_MAP_PNG = "/mapPNG/"
GAME_TAKE_TURN = "/takeTurn"
GAME_END_TURN = "/endTurn"
GAME_MAP_OBJECTS = "/mapObjects"
GAME_ACTION = "/action"
GAME_GET_ALL = "/all"
GAME_CONNECT = "/connect"
GAME_POST_ACTION_AND_TAKE_TURN = "/act"

# ACTIONS
MOVE_UP = "MOVE_UP"
MOVE_DOWN = "MOVE_DOWN"
MOVE_LEFT = "MOVE_LEFT"
MOVE_RIGHT = "MOVE_RIGHT"
ATTACK_UP = "ATTACK_UP"
ATTACK_DOWN = "ATTACK_DOWN"
ATTACK_LEFT = "ATTACK_LEFT"
ATTACK_RIGHT = "ATTACK_RIGHT"
PUT_UP_SETTLEMENT = "PUT_ON_SETTLEMENT"
RECRUIT_UNIT_SETTLERS = "RECRUIT_UNIT_SETTLERS"
RECRUIT_UNIT_WARRIORS = "RECRUIT_UNIT_WARRIORS"
WAIT = "WAIT"

actions = {0: MOVE_UP,
           1: MOVE_LEFT,
           2: MOVE_DOWN,
           3: MOVE_RIGHT,
           4: ATTACK_UP,
           5: ATTACK_DOWN,
           6: ATTACK_LEFT,
           7: ATTACK_RIGHT,
           8: PUT_UP_SETTLEMENT,
           9: RECRUIT_UNIT_SETTLERS,
           10: RECRUIT_UNIT_WARRIORS}

